export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const ADDING_CLIENT = 'ADDING_CLIENT';
export const ADD_CLIENT_SUCCESS = 'ADD_CLIENT_SUCCESS';
export const ADD_CLIENT_FAIL = 'ADD_CLIENT_FAIL';

export const UPDATING_CLIENT = 'UPDATING_CLIENT';
export const UPDATE_CLIENT_SUCCESS = 'UPDATE_CLIENT_SUCCESS';
export const UPDATE_CLIENT_FAIL = 'UPDATE_CLIENT_FAIL';

export const LOADING_CLIENT = 'LOADING_CLIENT';
export const LOAD_CLIENT_SUCCESS = 'LOAD_CLIENT_SUCCESS';
export const LOAD_CLIENT_FAIL = 'LOAD_CLIENT_FAIL';

export const DELETING_CLIENT = 'DELETING_CLIENT';
export const DELETE_CLIENT_SUCCESS = 'DELETE_CLIENT_SUCCESS';
export const DELETE_CLIENT_FAIL = 'DELETE_CLIENT_FAIL';

export const UPDATING_INPUT_SETTING= 'UPDATING_INPUT_SETTING';
export const UPDATING_INPUT_SETTING_SUCCESS= 'UPDATING_INPUT_SETTING_SUCCESS';
export const UPDATING_INPUT_SETTING_FAIL= 'UPDATING_INPUT_SETTING_FAIL';


export const ADD_TEMPLATE_SUCCESS = 'ADD_TEMPLATE_SUCCESS';
export const DELETE_TEMPLATE_SUCCESS = 'DELETE_TEMPLATE_SUCCESS';
export const UPDATE_TEMPLATE_SUCCESS = 'UPDATE_TEMPLATE_SUCCESS';

export const LOADING_RECENT_SUMMARY= 'LOADING_RECENT_SUMMARY';
export const LOADING_RECENT_SUMMARY_SUCCESS= 'LOADING_RECENT_SUMMARY_SUCCESS';
export const LOADING_RECENT_SUMMARY_FAIL= 'LOADING_RECENT_SUMMARY_FAIL';

export const DELETING_RECENT_SUMMARY= 'DELETING_RECENT_SUMMARY';
export const DELETING_RECENT_SUMMARY_SUCCESS= 'DELETING_RECENT_SUMMARY_SUCCESS';
export const DELETING_RECENT_SUMMARY_FAIL= 'DELETING_RECENT_SUMMARY_FAIL';

export const GET_TOTAL_PAGES = 'GET_TOTAL_PAGES'

export const SET_SUCCESS = 'SET_SUCCESS';

export const LOG_OUT = 'LOG_OUT';